spring:

  datasource:
    url: jdbc:h2:mem:abcbankdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
    initialization-mode: always
    data: classpath:data.sql
    continue-on-error: true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      current_session_context_class: org.springframework.orm.hibernate5.SpringSeccionContext
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      continue-on-error: false
      mode: always
