logging:
  file:
    name: ./ABCBank.log
  level:
    root: INFO

management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
#        include: httptrace, "*"
        include: beans, health, info, logfile, loggers, metrics, httptrace, env
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ./ABCBank.log
  info:
    app:
      name: ABCBank
      description: This is my first spring boot application whith actuator
      version: 1.0.0

